<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="abstractJJD" nsURI="abstractJJD" nsPrefix="abstractJJD">
  <eAnnotations source="gmf"/>
  <eClassifiers xsi:type="ecore:EClass" name="ModelFactoryAbstractJJD">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="listPackagesJJD" upperBound="-1"
        eType="#//PackageJJD" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PackageJJD">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nameSpace" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="subPackagesJJD" upperBound="-1"
        eType="#//PackageJJD" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="listClassJJD" upperBound="-1"
        eType="#//ClassJJD" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ClassJJD">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isAbstract" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="listAttributesJJD" upperBound="-1"
        eType="#//AttributeJJD" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="listMethodsJJD" upperBound="-1"
        eType="#//MethodJJD" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="listRelationsJJD" upperBound="-1"
        eType="#//RelationJJD" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AttributeJJD">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MethodJJD">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="modifier" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="semantic" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="returnType" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="listAttributesJJD" upperBound="-1"
        eType="#//AttributeJJD" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RelationJJD">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="rolA" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="rolB" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="navigabilityA" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="navigabilityB" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="multiplicityA" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="multiplicityB" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" eType="#//ClassJJD"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" eType="#//ClassJJD"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AgregationJJD" eSuperTypes="#//RelationJJD"/>
  <eClassifiers xsi:type="ecore:EClass" name="InheritanceJJD" eSuperTypes="#//RelationJJD"/>
  <eClassifiers xsi:type="ecore:EClass" name="ContainmentJJD" eSuperTypes="#//RelationJJD"/>
  <eClassifiers xsi:type="ecore:EClass" name="AssociationJJD" eSuperTypes="#//RelationJJD"/>
  <eClassifiers xsi:type="ecore:EClass" name="ImplementJJD" eSuperTypes="#//RelationJJD"/>
</ecore:EPackage>
